version: '3'

services:
  emit-sassy-node:
    build: .
    image: emit-sassy-node
    container_name: emit-sassy-node
    entrypoint: sh -c "npm i"
    tty: true
    restart: "no"
    volumes:
      - .:/var/www
